### ISSUE TITLE
Ctrl+Click with multiple open root elements does not behave as expected

### ISSUE THREAD

**Issue by brodriguez8774** [DJBarnes/django-dump-die#7] opened 2022-03-25 17:22 UTC
Ctrl+Click on the first root element will work as expected, and fully expand all levels of children within.

Ctrl+Click on any further root elements (before closing the first) will minimize all levels of the first root element, and then only open the first level of the newly clicked element.

This "incorrect" behavior seems to persist until all root elements are closed once more.

**Comment by DJBarnes** [comment] 2022-04-01 19:09
Need more information as I don't seem to experience this. Are you talking about when the second root element is a duplicate of the first? As in dumpling the same thing multiple times? If so, it is pseudo-fixed now.

**Comment by brodriguez8774** [comment] 2022-04-04 17:34
I can consistently replicate issue, on both firefox and chrome, so it doesn't seem browser dependent.

Occurs when any two (or more) root objects are ctrl+clicked, regardless of if they are duplicates or not.

First ctrl+clicked root object will behave as expected. Any further will break functionality until all root objects are fully minimized once more.

**Closed** 2022-04-06 19:12 UTC
Labels: bug
